[build]
builder = "nixpacks"
buildCommand = "dotnet publish StepCounter.Api/StepCounter.Api.csproj -c Release -o out"

[deploy]
startCommand = "dotnet out/StepCounter.Api.dll"
healthcheckPath = "/"
healthcheckTimeout = 100 